eduNEXT/drydock

README.rst, drydock/manifest_builder/infrastructure/tutor_based_manifests.py
This adds an additional manifest builder that creates an additional overlay on top of the ones generated by `BaseManifests`. `ExtendedManifests` will take the path defined in `extra_templates` in your drydock reference and render the templates living there on to your drydock-env.
1. Modify you reference to include:
```yaml
manifest_class: drydock.manifest_builder.infrastructure.tutor_based_manifests.ExtendedManifest
manifest_options:
extra_templates: extra_templates_root
```
2. Create the directories `extra_templates_root/extra-extensions` and add a `kustomization.yml` with you additional resources. Remember that this is a template and you have access to all the variables (e.g. `{{ K8S_NAMESPACE }}`).
3. Run `tutor drydock save -r reference.yml` to generate the new environment.
=> Add extension points to the BaseManifest repository

README.rst, drydock/manifest_builder/infrastructure/tutor_based_manifests.py
This adds an additional manifest builder that creates an additional overlay on top of the ones generated by `BaseManifests`. `ExtendedManifests` will take the path defined in `extra_templates` in your drydock reference and render the templates living there on to your drydock-env.
1. Modify you reference to include:
```yaml
manifest_class: drydock.manifest_builder.infrastructure.tutor_based_manifests.ExtendedManifest
manifest_options:
extra_templates: extra_templates_root
```
2. Create the directories `extra_templates_root/extra-extensions` and add a `kustomization.yml` with you additional resources. Remember that this is a template and you have access to all the variables (e.g. `{{ K8S_NAMESPACE }}`).
3. Run `tutor drydock save -r reference.yml` to generate the new environment.
> Ditto of …
=> Add kustomize based extensions to the base manifests

drydock/templates/kustomized/tutor13/extensions/ingress.yml
This change just slipped through the last PR.
=> fix: go back to production ingress

drydock/templates/kustomized/tutor13/extensions/drydock-jobs/forum.yml, drydock/templates/kustomized/tutor13/extensions/drydock-jobs/notes.yml
There was a typo on the init command for the forum-job. Additionally some useful annotations for ArgoCD were missing from the notes jobs.
=> fix: use the correct init command for forum and add missing annotations

drydock/templates/kustomized/tutor13/extensions/hpa.yml, drydock/templates/kustomized/tutor13/extensions/overrides.yml
This PR aims to mitigate a couple of issues:
- Forum pod won't start appropriately unless the Forum initialization job has been run first. For this reason, I moved the Forum pod deployment to a later wave in argoCD (4)
- HPA resource creation fails if the deployments related to them are not yet created. This motivated the creation of a new wave (5) to apply the HPA.
At this point we are tightly coupled with ArgoCD, without it our initialization strategy won't work. Are we comfortable with this?
=> feat: Forum pod to W4, HPA to W5

drydock/templates/kustomized/tutor13/extensions/drydock-jobs/cms.yml, drydock/templates/kustomized/tutor13/extensions/drydock-jobs/forum.yml, drydock/templates/kustomized/tutor13/extensions/drydock-jobs/lms.yml, drydock/templates/kustomized/tutor13/extensions/drydock-jobs/minio.yml, drydock/templates/kustomized/tutor13/extensions/drydock-jobs/mysql.yml, drydock/templates/kustomized/tutor13/extensions/drydock-jobs/notes.yml, drydock/templates/kustomized/tutor13/extensions/kustomization.yml
This PR configures a patch to remove all jobs whose name contains the word "mysql" when MySQL service is running outside the K8S cluster. This solution is based on the discussion on [this thread](https://github.com/kubernetes-sigs/kustomize/issues/4526).
I'm wondering if this solution is too wide, removing other jobs related to MySQL we would like to keep. Should we identify MySQL initialization tasks with an specific label?
=> feat: removing MySQL jobs when MySQL running outside the cluster

drydock/manifest_builder/infrastructure/tutor_based_manifests.py
This PR makes the template root for manifests generation configurable using the drydock reference, for example:
```
drydock:
builder_class:  drydock.manifest_builder.application.manifest_builder.ManifestBuilder
config_class: drydock.manifest_builder.infrastructure.tutor_config.TutorExtendedConfig
manifest_class: drydock.manifest_builder.infrastructure.tutor_based_manifests.ExtendedManifests
manifest_options:
output: "env"
template_root: "tutor14"
```
Without this, we couldn't manually shift between templates without changing the implementation.
You could use PR #18
=> feat: make manifests template root configurable through reference

drydock/templates/kustomized/tutor14/extensions/drydock-jobs/notes.yml
This PR adds missing target-service/runner-service labels to the notes jobs.
=> fix: add missing labels for notes jobs

drydock/templates/kustomized/tutor13/extensions/kustomization.yml, drydock/templates/kustomized/tutor13/extensions/multipurpose-jobs.yml
This PR adds a patch to enable multipurpose jobs in an OpenedX installation. This feature is thought to include jobs that are run regularly that are not part of the platform initialization. Examples of these tasks are:
- User retirement routines
- Old access tokens cleaning
=> feat: multipurpose jobs

drydock/templates/kustomized/tutor14/extensions/kustomization.yml, drydock/templates/kustomized/tutor14/extensions/multipurpose-jobs.yml
This PR adds a patch to enable multipurpose jobs in OpenedX installations generated with V14 templates. Quite similar to https://github.com/eduNEXT/drydock/pull/22
=> feat: multipurpose jobs V14

drydock/templates/kustomized/tutor14/extensions/kustomization.yml
The patch used to skip the MySQL initialization jobs when running the MySQL service outside of the Instance was missing.
=> fix: add missing patch in V14 templates

drydock/templates/kustomized/tutor13/extensions/debug/deployments.yml, drydock/templates/kustomized/tutor14/extensions/debug/deployments.yml
This PR adds the needed configuration for container interactivity using tools like pudb/pdb for debugging purposes.
1. After enabling the debugging services (check the instructions in [this PR](https://github.com/eduNEXT/drydock/pull/25) for a how to test), increase the number of replicas to 1 (if not already)
2. Enter the container, then install nano if needed
3. Modify `nano /openedx/edx-platform/common/djangoapps/student/views/dashboard.py` adding a breakpoint in the student_dashboard view (easy to test)
4. Attach to the container: `k attach -it lms-debug-XXXXX-XXXXX`
5. Enter the student dashboard
=> feat: add configuration for container interactivity

drydock/templates/kustomized/tutor13/extensions/debug/deployments.yml, drydock/templates/kustomized/tutor14/extensions/debug/deployments.yml
This PR increases the default number of replicas for the debug deployments to avoid issues with self-healing argocd configurations -so it doesn't remove the debugging pods while synchronizing-.
=> refactor: increase default debug replicas to at least one

.github/workflows/release.yml, CHANGELOG.md, setup.cfg
This PR adds a github workflow triggered manually by shipyard maintainers:
1. Executes a dryrun to obtain the next tag version
2. Based on the next tag version, generates the new changelog entry
3. Uses bumpversion library to update strings in the library
4. Executes again the action that generates the tag, this time it pushes the tag to the main branchry
5. Generates a draft release
This workflow can be changed based on what we want our release workflow to be, I'm open to suggestions.
=> feat: add release GitHub workflow

.github/CODEOWNERS, catalog-info.yaml
This PR adds a basic catalog and assigns the code to @eduNEXT/shipyard-crew
=> chore: adding backstage catalog and owners

drydock/templates/kustomized/tutor13/extensions/drydock-jobs/lms.yml, drydock/templates/kustomized/tutor13/extensions/overrides.yml, drydock/templates/kustomized/tutor14/extensions/debug/deployments.yml, drydock/templates/kustomized/tutor14/extensions/drydock-jobs/lms.yml, drydock/templates/kustomized/tutor14/extensions/overrides.yml, drydock/templates/kustomized/tutor15/extensions/debug/deployments.yml
A compilation of small fixes that address:
- cms debug pods don't define the `DJANGO_SETTINGS_MODULE` variable.
- The `DRYDOCK_CMS_SSO_USER` variable is not being used in the actual command.
- Triming whitespace in certain places generates invalid yaml.
=> Small fixes: CMS_SSO_USER, cms debug pods and whitespace triming

drydock/templates/kustomized/tutor14/extensions/overrides.yml
This PR fixes an issue when rendering Drydock overrides for NewRelic. Without this change, the output looks like this:
`---apiVersion: apps/v1`
which breaks the YAML format.
=> fix: rendering NewRelic overrides properly in tutor14 Drydock templates

drydock/manifest_builder/infrastructure/tutor_based_manifests.py, setup.py
This PR fixes an error ocurred when use Drydock v0.7.0 with tutor version older than palm (v16.0.0).
=> fix: drydock fails in older versions to tutor palm

drydock_backups/Dockerfile, drydock_backups/docker-entrypoint.sh, drydock_backups/patches/drydock-multipurpose-jobs, drydock_backups/plugin.py
This PR fixes the path to use in db backup to /data which is mounted by PVC. 
Also changes the cronjob to just run the docker entrypoint with arg and changes the docker image.
I was testing on [yamato-dunkirk](https://argocd.services.stage.edunext-shipyard.net/applications/dunkerque-openedx?operation=false&resource=)
=> fix: set the correct path to use pvc volume

drydock_backups/README.rst
This PR update the `Readme` file changed the instructions for build the [shipyard-utils](https://hub.docker.com/r/ednxops/shipyard-utils/tags) docker image
=> doc: update instructions for build docker image

.github/workflows/release.yml
This PR removes unused ATLAS_PAT due to we're currently have the main branch unprotected.
=> fix: remove pat from release workflow

drydock/patches/kustomization
Currently, the first initialization of the "LMS" and "CMS" deployment modules fails when trying to look up tables before they were migrated in the jobs with ArgoCD  Waves. This PR fixes the issue by placing these two deployments in the fourth wave after the jobs were run.
=> fix: issue at first run with lms and cms deployments

setup.py
This PR constraints the Tutor version to use the latest Olive version
=> feat: version constraint for Drydock

drydock/templates/drydock/k8s/ingress/issuer.yml
This PR adds a secret for the custom cert.
=> fix: add missing drydock custom certs secret

drydock/templates/drydock/k8s/drydock-jobs/notes.yml
Default tutor jobs are skipped due to an error with ArgoCD, the skip match is based on `app.kubernetes.io/component: job`, there are some missing annotations that need to be fixed in this PR.
=> fix: notes annotations throw job skip from argocd sync

drydock/templates/drydock/k8s/drydock-jobs/cms.yml, drydock/templates/drydock/k8s/drydock-jobs/lms.yml, drydock/templates/drydock/k8s/drydock-jobs/minio.yml, drydock/templates/drydock/k8s/drydock-jobs/mongodb.yml, drydock/templates/drydock/k8s/drydock-jobs/mysql.yml, drydock/templates/drydock/k8s/drydock-jobs/notes.yml
If we run scripts using `bash -c "..."` the container that is running the command will run succesfuly if the last comand return 0 as a status code, even if intermediate commands may have failed, to avoid this we add `-e` flag to fail early on any error.
=> fix: run the jobs scripts with '-e' to exit on error

README.rst, drydock/patches/kustomization, drydock/plugin.py, drydock/templates/drydock/k8s/lifecycle/cms.yml, drydock/templates/drydock/k8s/lifecycle/lms.yml, drydock/templates/drydock/k8s/patches/post-init-deployments-sync-wave.yml
The LMS-WORKER, CMS-WORKER and FORUM deployments are failing when you need to create database users first. 
This changes are made to take the critical deployments on the sync wave 100, adding a list to allow the env to add more just in case.
=> fix: add deployments to sync wave 100

README.md, drydock/patches/caddyfile, drydock/patches/caddyfile-cms, drydock/patches/caddyfile-lms, drydock/templates/drydock/k8s/ingress/cms.yml, drydock/templates/drydock/k8s/ingress/lms.yml
This PR fixes an issue with the scorm functionality where it failed to render the templates because the `tutor-contrib-s3` plugin was not installed.
=> fix: enable scorm proxy if s3 plugin is installed

drydock/patches/caddyfile, drydock/patches/caddyfile-cms, drydock/patches/caddyfile-lms, drydock/templates/drydock/k8s/ingress/cms.yml, drydock/templates/drydock/k8s/ingress/lms.yml
Small bug fix to cover the case where the minio host is defined too
=> fix: verify minio host is defined on scorm proxy

.github/workflows/kubeconform-validation.yml
This PR include a fix to the `Check k8s manifests` workflow to resolve the error:
```
invalid value "latest" for flag -kubernetes-version: latest is not a valid version. Valid values are "master" (default) or full version x.y.z (e.g. "1.27.2")
```
=> fix: solve error check k8s workflow olive

.github/workflows/kubeconform-validation.yml
This PR include a fix to the `Check k8s manifests` workflow to resolve the error:
```
invalid value "latest" for flag -kubernetes-version: latest is not a valid version. Valid values are "master" (default) or full version x.y.z (e.g. "1.27.2")
```
=> fix: solve error check k8s workflow palm

drydock/patches/openedx-common-settings
The S3Boto3Storage backend no longer accepts the argument bucket. Use bucket_name or the setting AWS_STORAGE_BUCKET_NAME instead: https://github.com/jschneier/django-storages/pull/636
This PR fixes this error in quince installations using django-storages 1.14:
```
File "/openedx/edx-platform/./lms/envs/tutor/production.py", line 255, in scorm_xblock_storage
return S3Boto3Storage(
File "/openedx/venv/lib/python3.8/site-packages/storages/backends/s3.py", line 280, in __init__
super().__init__(**settings)
File "/openedx/venv/lib/python3.8/site-packages/storages/base.py", line 15, in __init__
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Invalid setting 'bucket' for S3Storage
```
=> fix: replace deprecated bucket argument for recommended bucket_name

pyproject.toml
This PR ignores the following commit mesagges to be included in the changelog and release notes
docs
build
style
chore
test
=> ci: ignore commits in changelog and release notes - palm

pyproject.toml
This PR ignores the following commit mesagges to be included in the changelog and release notes
docs
build
style
chore
test
=> ci: ignore commits in changelog and release notes - olive

pyproject.toml
This PR ignores the following commit mesagges to be included in the changelog and release notes
docs
build
style
chore
test
=> ci: ignore commits in changelog and release notes

.github/environments/enabled/config.yml, README.md, drydock/patches/kustomization-resources, drydock/plugin.py, drydock/templates/drydock/k8s/ingress/static-cache.yml
This PR allows the setup of a configurable static cache running on NGINX. Make sure to configure the following snippet to your nginx HTTP config:
```nginx
proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=static-cache:32m use_temp_path=off max_size=4g inactive=24h;
proxy_cache_key $scheme$proxy_host$request_uri;
proxy_cache_lock on;
proxy_cache_use_stale updating;
proxy_ignore_headers Cache-Control;
```
Using k6 for fetching multiple static files.
Before:
```
/\      |‾‾| /‾‾/   /‾‾/   
/\  /  \     |  |/  /   /  /    
/  \/    \    |     (   /   ‾‾\  
/          \   |  |\  \ |  (‾)  | 
/ __________ \  |__| \__\ \_____/ .io
execution: local
script: openedx-testing/mfe/request_static_files.js
output: -
scenarios: (100.00%) 1 scenario, 400 max VUs, 1m0s max duration (incl. graceful …
```
=> feat: add support for static cache config

.github/environments/enabled/config.yml, README.md, drydock/patches/kustomization-resources, drydock/plugin.py, drydock/templates/drydock/k8s/ingress/static-cache.yml
backport of https://github.com/eduNEXT/drydock/pull/106
=> feat: add support for static cache config (quince)

drydock/templates/drydock/k8s/patches/hpa-sync-wave.yml
The HPA sync-wave patch includes annotations to indicate argocd in which order should the HPA resources be applied in relation to the other resources. The `argocd.argoproj.io/hook: Sync` and `argocd.argoproj.io/hook-delete-policy: HookSucceeded` annotations are used for ephemeral resources (like jobs) and should not be used for the HPA resources.
Install https://github.com/eduNEXT/tutor-contrib-pod-autoscaling and activate the HPAs. The resources should be missing in the ArgoCD UI. Apply the fix and they should appear again.
=> fix: remove unnecesary annotations from the hpa sync wave

drydock/templates/drydock/k8s/patches/hpa-sync-wave.yml
Backport of https://github.com/eduNEXT/drydock/pull/117
=> fix: remove unnecesary annotations from the hpa sync wave (quince)

drydock/templates/drydock/k8s/patches/hpa-sync-wave.yml
backport of https://github.com/eduNEXT/drydock/pull/117
=> fix: remove unnecesary annotations from the hpa sync wave (palm)

drydock/patches/caddyfile, drydock/patches/caddyfile-cms, drydock/patches/caddyfile-lms, drydock/templates/drydock/k8s/ingress/cms.yml, drydock/templates/drydock/k8s/ingress/lms.yml
When enabling SCORM features, a set of patches are applied on caddy/ingress objects so the LMS/CMS services are used as proxies to serve SCORM resources. The backend for such proxies is the storage system used in an installation, generally MinIO, AWS S3, or an S3-compatible storage system.
When using [tutor-contrib-s3](https://github.com/hastexo/tutor-contrib-s3), we hardcode the backend URL for SCORM to `{{ S3_STORAGE_BUCKET }}.s3.amazonaws.com`. However, you can use this plugin with other S3-compatible systems, not only AWS, thus we need to provide flexibility to replace the `s3.amazonaws.com` domain with the custom storage system domain.
This PR aims to provide such flexibility and set the backend URL for SCORM to `{{ S3_STORAGE_BUCKET }}.{{ S3_HOST|default('s3.amazonaws.com', true) …
=> fix: S3_HOST for alternative S3-compatible services

drydock/patches/uwsgi-config
This PR fixes the issue with closed connections which causes 502 responses.
Closed connection after POST request: https://github.com/unbit/uwsgi/issues/2133. The fix: https://github.com/unbit/uwsgi/issues/1097#issuecomment-1323662862
More information on uwsgi production deployments: https://www.bloomberg.com/company/stories/configuring-uwsgi-production-deployment/ 
The other tweaks are some community recommendations:
https://github.com/nginxinc/kubernetes-ingress/issues/143#issuecomment-347814243
This has been tested with multiple tweaks, here are the k6 results:
```
1. Default k8s deployments:
data_received..................: 8.8 MB 64 kB/s
data_sent......................: 294 kB 2.1 kB/s
http_req_blocked...............: avg=54ms    min=455ns    med=1.13µs   max=802.08ms p(90)=2.17µs …
```
=> fix: add uwsgi tweaks for closed connection

drydock/patches/openedx-common-settings, drydock/patches/uwsgi-config, drydock/templates/drydock/k8s/lifecycle/cms.yml, drydock/templates/drydock/k8s/lifecycle/lms.yml
This PR:
- Disable uwsgi request logging
- Disable `tracking.log` and `all.log` files for lms and cms pods.
- Removes the prestop hook in favor of a uwsgi hook call to gracefully terminate workers, which improved the time needed to restart or terminate lms/cms pods while being able to answer pending requests
- Adds livenessProbe for pods.
- Adds a soft pod AntiAffinity to prefer scheduling pods across nodes.
- Setups maxUnavailable to 0 to safely rollout deployments without losing capacity.
- Setups maxSurge to 2 so as not to overcommit resources temporarily for a deployment.
=> fix: add readiness probe for lms/cms

drydock/patches/openedx-common-settings, drydock/patches/uwsgi-config, drydock/templates/drydock/k8s/lifecycle/cms.yml, drydock/templates/drydock/k8s/lifecycle/lms.yml
* fix: add readiness probe for lms/cms
* fix: add readiness probe for lms/cms
* fix: add affinity to spread lms/cms to multiple nodes
* chore: remove readiness probe
* fix: reduce startup probe period seconds
* fix: gracefully kill uwsgi workers
* fix: disable local file loggers
* fix: disable logging
* fix: reduce max unavailable to 0
* fix: add liveness probe for cms and lms
* fix: fail early on tracking logger removal
* chore: remove rolling update options
* fix: restore preStop hook
* fix: use right host for cms livenessProbe
* fix: use lms/cms host only
* chore: restore prestopHook
(cherry picked from commit f970e0102f36c3064201ff7be317d1a908557a87)
=> fix: add readiness probe for lms/cms (#133)

drydock/patches/openedx-common-settings
This PR closes #135. It was tested on Seward.
- CMS view: https://studio.redwood.releases.edunext.link/container/block-v1:demo+demox+01+type@vertical+block@cc931782487c49318bda8cc385db1516#
- LMS View: https://demo.redwood.releases.edunext.link/learning/course/course-v1:demo+demox+01/block-v1:demo+demox+01+type@sequential+block@971737e543204551bb34c4ca44e12b86/block-v1:demo+demox+01+type@vertical+block@cc931782487c49318bda8cc385db1516
- Preview: https://preview.redwood.releases.edunext.link/courses/course-v1:demo+demox+01/courseware/d6780558bc3042c7ab6dd441a06d3478/971737e543204551bb34c4ca44e12b86/6?activate_block_id=block-v1%3Ademo%2Bdemox%2B01%2Btype%40vertical%2Bblock%40cc931782487c49318bda8cc385db1516
=> fix(scorm): use request host for scorm custom domain

drydock/plugin.py, drydock/templates/drydock/k8s/newrelic.yml, pyproject.toml
The location of the uwsgi.ini file was changed in [tutor==18.1.3](https://github.com/overhangio/tutor/pull/1036) so we have to update the command run by the container. Additionally we remove an unused variable that was lingering.
=> fix(newrelic): use the new location of uwsgi.ini in the launch command

drydock/templates/drydock/task/mongodb/init
This PR aims to:
- Include the MongoDB port in the mongosh command (useful when running MongoDB in a different port)
- Include the [replica set info in the mongosh command](https://www.mongodb.com/docs/mongodb-shell/reference/options/#std-option-mongosh.--host). It could be the case you aren't connected to a replica set primary but to a secondary one. If the replica set name is not specified, the mongosh command will fail since it is not possible to write to a secondary
=> fix: adding replicaset info to mongosh connection command.

.github/workflows/release.yml, Makefile, pyproject.toml
This PR adds a workflow to upload package to pypi
=> build: add workflow to upload package to pypi

.github/environments/minio_enabled/config.yml, .github/requirements.txt, .github/workflows/release.yml, README.md, drydock/plugin.py, drydock/templates/drydock/k8s/ingress/cms.yml, drydock/templates/drydock/k8s/ingress/lms.yml, pyproject.toml
This intends to add support to sumac release from tutor.
=> feat: sumac release

drydock/patches/openedx-common-settings, drydock/plugin.py, drydock/templates/drydock/task/mongodb/init
The tutor-forum plugin hardcodes the value of the name of the forum
database in the Django settings, dropping the previous
`FORUM_MONGODB_DATABASE` setting (https://github.com/overhangio/tutor-forum/blob/5d3d2dd7d1ea3c9a311ac5619eb5931a111ba363/tutorforum/plugin.py#L29).
We reintroduce the `FORUM_MONGODB_DATABASE` setting and ensure the
mongodb user has permissions over the Forum Database.
In order to be able to override the hardcoded value we lower the
priority level of the Drydock patches, guaranteeing that they are going
to be applied after all the installed plugins.
=> fix: adjust permissions for custom named forum dbs

README.md, drydock/patches/kustomization, drydock/patches/kustomization-resources, drydock/plugin.py, drydock/templates/drydock/k8s/patches/add-image-pull-secret-cronjob.yml, drydock/templates/drydock/k8s/patches/add-image-pull-secret.yml, drydock/templates/drydock/k8s/patches/image-pull-secret.yml, drydock/templates/drydock/k8s/secrets/image-pull-secret.yml
This PR creates the new Secret for include additionals registry credentials
In `config.yaml` you must add the configuration like this:
```yaml
DRYDOCK_REGISTRY_CREDENTIALS: '{"auths":{"https://index.docker.io/v1/":{"auth":"dXNlcjpwYXNz"}}}'
```
=> feat: create patch for registry credentials

.github/workflows/release.yml
This is a similar error to the one described here:
https://github.com/eduNEXT/tutor-contrib-codejail/pull/66
=> ci: fix PyPI publishing
